# DEFAULT
server:
  port: 8080
  servlet:
    context-path: /api

# 임시값
encryptor:
  key: blaybus

# JWT
spring:
  jwt:
    expire:
      access: 3600000
      refresh: 1209600000

    secret: 5pgPHgSG60zNed0BD1+gek7NuV7HZXZwqgO25KDzKzA=

  profiles:
    active: local
    include: key

  #JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    sql:
      init:
        mode: always


#Swagger
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

---
#Local 개발 프로필
spring:
  config:
    activate:
      on-profile: local

  # Security Registration (Provider Skip)
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ENC(0a2OroHBUVfWE6VktU1pC4ln7Q3gr7LkD/HA8b1LloPyGoalqpcbhINOvGFrQyQXOOwaLFHSiYubaO9eBH4spg9k4B1TILH0fEqT+FO+Iet7bnci+UDjyA==)
            client-secret: ENC(ZXKqTbZknNGLctERRJdhGmaRhXR1CZ9L2zrMeq3IwbS8nEX4Nx4vMyKnjsD1vipn)
            redirect-uri: http://localhost:8080/api/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

 #maria DB로 변경
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${local-db.url}
    username: ${local-db.username}
    password: ${local-db.pw}

# 로그인 성공 시 URL
redirect:
  url: http://localhost:8080/api/member
  onboarding:
    url: http://localhost:8080/api/member

---
#Prd 프로필
spring:
  config:
    activate:
      on-profile: prd

  # Security Registration (Provider Skip)
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ENC(0a2OroHBUVfWE6VktU1pC4ln7Q3gr7LkD/HA8b1LloPyGoalqpcbhINOvGFrQyQXOOwaLFHSiYubaO9eBH4spg9k4B1TILH0fEqT+FO+Iet7bnci+UDjyA==)
            client-secret: ENC(ZXKqTbZknNGLctERRJdhGmaRhXR1CZ9L2zrMeq3IwbS8nEX4Nx4vMyKnjsD1vipn)
            redirect-uri: https://playbus-hair-back-24bd2f0b794a.herokuapp.com/api/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

  # DB 설정
  datasource:
    url: ${DB_HOST}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  #JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

# 로그인 성공 시 URL
redirect:
  url: http://hair-fe-smoky.vercel.app/home
  onboarding:
    url: http://hair-fe-smoky.vercel.app/home
---
# Dev
spring:
  config:
    activate:
      on-profile: dev

  # Security Registration (Provider Skip)
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ENC(0a2OroHBUVfWE6VktU1pC4ln7Q3gr7LkD/HA8b1LloPyGoalqpcbhINOvGFrQyQXOOwaLFHSiYubaO9eBH4spg9k4B1TILH0fEqT+FO+Iet7bnci+UDjyA==)
            client-secret: ENC(ZXKqTbZknNGLctERRJdhGmaRhXR1CZ9L2zrMeq3IwbS8nEX4Nx4vMyKnjsD1vipn)
            redirect-uri: http://ec2-3-36-62-125.ap-northeast-2.compute.amazonaws.com:8080/api/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

  # DB 설정
  datasource:
    url: ${DB_HOST}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  #JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

# 로그인 성공 시 URL
redirect:
  url: http://localhost:5173/home
  onboarding:
    url: http://localhost:5173/home