# DEFAULT
server:
  port: 8080
  servlet:
    context-path: /api

# JWT
spring:
  jwt:
    expire:
      access: 3600000
      refresh: 1209600000

#    secret: ENC(FZm2+cnNzBUJNDxOUQFnvLAXbbvCJtgr+kRiw4avSMhdYVmMOyqnQMJ1Xprtr2oslRDtdew6FNcEJschjZzcW9PQEPgufl1uJuga5slxY00=)

  profiles:
    active: local
    include: key

  #JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
    # SQL 포매터
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode: always

#Swagger
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

---
#Local 개발 프로필
spring:
  config:
    activate:
      on-profile: local

# maria DB로 대체
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: ${local-db.url}
#    username: ENC(995yKJ+4XySjW/FqXijcsw==)
#    password: ${local-db.pw}

---
#Dev 프로필
spring:
  config:
    activate:
      on-profile: dev

#  데이터베이스 연동 필요
  datasource:
    url: ENC(cYdS1V7cLnCsn4wojCdiCQhyQd1J72zlLu6GIxQUYllj+Uwn5Mt+fIytyuJT17aRNmzhYhu1DvxIacJAexe9m5iydghLty0HgZZ/tS7JjCEmjP0f9qE2ow==)
    username: ENC(KlpDcGHRN9vXvSjoKPZoXg==)
    password: ENC(+BQknx5kOfehm8UGVEhMjka9oqRmRVta)
    driver-class-name: org.mariadb.jdbc.Driver